### ISSUE TITLE
Getting Crash on Startup

### ISSUE THREAD

**Issue by Boolyman** [Team-Rapture/Aquatic#1]
Crash Report: https://pastebin.com/N87ByqjB

**Comment by Radient-Sora** [comment]
Question did you make any changes to the config just checking some values

**Comment by Boolyman** [comment]
I dont even think a config generated yet... it was the very first time I installed the mod.

**Comment by Boolyman** [comment]
Ah, I just checked, the file did generate.  But no, I didnt make any changes.

**Comment by Radient-Sora** [comment]
Alrighty I'ma do some checks

**Comment by Radient-Sora** [comment]
Do you think you can send me a modpack import file so I can do farther testing wanna make sure it's 100% on our end

**Comment by P3rf3ctXZer0** [comment]
Hey so this is a dedicated server crash on startup - This is with a pre existing world.
https://gist.github.com/P3rf3ctXZer0/2f1878004165a16b27b513a40bc753f0

**Comment by UpcraftLP** [comment]
fixed in Aquatic [1.0.0-c](https://minecraft.curseforge.com/projects/aquatic/files/2548573 "CurseForge Download")
