### ISSUE TITLE
Crash when accessing Controls Screen

### ISSUE THREAD

**Issue by ScottoMotto** [Team-Rapture/Aquatic#5]
When a world is open attempting to access the Options - Controls keybind manager screen the following crash occurs: https://pastebin.com/sQFz9KU7

This is with no other mods installed and the recommended Forge version.

Note that you can access the Controls screen if no world in loaded.

**Comment by abused** [comment]
Someone be doing some bad things @UpcraftLP ?

**Comment by UpcraftLP** [comment]
fixed in the next build

**Comment by UpcraftLP** [comment]
released an alpha on curse that has the bug fixed.
[Download Link](https://minecraft.curseforge.com/projects/aquatic/files/2593043 "CurseForge")
