### ISSUE TITLE
Server Controls Crash

### ISSUE THREAD

**Issue by Mixheart** [Team-Rapture/Aquatic#7]
When in-game on a singleplayer server. Crash upon clicking Controls in options. 
[crash-2019-12-14_00.30.36-client.txt](https://github.com/Team-Rapture/Aquatic/files/3963631/crash-2019-12-14_00.30.36-client.txt)

**Comment by UpcraftLP** [comment]
duplicate of #5.
use the latest version https://www.curseforge.com/minecraft/mc-mods/aquatic/files/2593043
